### ISSUE TITLE
clear_changes_information

### ISSUE THREAD

**Issue by robertkurti** [mech/filemaker-ruby#13]
Hi,

Not sure if relevant or not ... but after upgrading to filemaker-ruby 1.0, we had to include public :clear_changes_information on all the models in order to make the app work.

**Comment by robertkurti** [comment]
Also, I am getting this for some reason:

This used to work fine on v0.19

`rake aborted!
NoMethodError: undefined method `where' for []:Array
Did you mean?  when
/Users/robertkurti/.gem/ruby/2.6.1/bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/relations/proxy.rb:40:in `method_missing'
/Users/robertkurti/workspace/completerails/lib/tasks/dashboard.rake:183:in `block (3 levels) in <top (required)>'
/Users/robertkurti/.gem/ruby/2.6.1/bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `block in each'
/Users/robertkurti/.gem/ruby/2.6.1/bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `each'
/Users/robertkurti/.gem/ruby/2.6.1/bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `each'
/Users/robertkurti/workspace/completerails/lib/tasks/dashboard.rake:174:in `block (2 levels) in <top (required)>'
/Users/robertkurti/.gem/ruby/2.6.1/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
Tasks: TOP => dashboard:update
(See full trace by running task with --trace)`

Bugsnag: 
`bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/relations/proxy.rb:40:in `method_missing': undefined method `where' for []:Array
Did you mean?  when (NoMethodError)
    from lib/tasks/dashboard.rake:183:in `block (3 levels) in <top (required)>'
    from bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `block in each'
    from bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `each'
    from bundler/gems/filemaker-ruby-4f11639a8a6a/lib/filemaker/model/criteria.rb:63:in `each'
    from lib/tasks/dashboard.rake:174:in `block (2 levels) in <top (required)>'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
    from gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
    from gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
    from gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
    from /Users/robertkurti/.rubies/ruby-2.6.1/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
    from gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
    from gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
    from gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
    from gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
    from gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
    from gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
    from gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
    from gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
    from gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
    from gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
    from gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
    from gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
    from bin/rake:23:in `load'
    from bin/rake:23:in `<main>'`

`
rfq_due_today: 0,
--
  | rfq_due_tomorrow: 0,
  | rfq_due_later: 0,
  | tickets_open: st.tickets.where(status_number: "1").count, <---- on this line
  | tickets_pending: st.tickets.where(status_number: "2").count,
  | timestamp: Time.now().in_time_zone("Europe/Paris"),
  | }
`

**Comment by mech** [comment]
Are you able to let me see how you setup your model?

Also can you point your gem to the latest Github path and test to see :)

```
gem 'filemaker', github: 'mech/filemaker-ruby'
```

**Comment by gingermusketeer** [comment]
Upgrading to the latest version on master has resolved this issue for us. I work with @robertkurti so I think this can be closed :)

**Comment by mech** [comment]
Good to know :)
